chore: add ci files
ipfs/helia pull request #17
Opened 2022-12-22 16:10 UTC by achingbrain

Adds github files for CI releases and dep/config updates.

2023-01-16 10:12 UTC, vmx commented
> * Creates a `~/.helia` directory on startup

I wonder if on Linux systems it should really be `~/.helia` or rather a [XDG Base Directory](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) friendly location. Using `$XDG_CONFIG_HOME/helia` instead of `~/.helia` seems to be the most straightforward thing to do (which would be ~/.config/helia` by default).

There's also `$XDG_DATA_HOME`, which according to the spec is for "user specific data files" (by default at `~/.local/share/`), which could be used for the data. That would probably be the "proper way", but other projects like Chromium e.g. also just store everything at a single directory at `$XDG_CONFIG_HOME` (except for the cache).

2023-01-16 10:31 UTC, achingbrain commented
Sounds good, though I guess we'd fall back to `~/.helia` if the `$XDG_*` env vars aren't defined.

On Mac OS config/data should be under `~/Library` & there's probably an equivalent for Windows too.

2023-02-03 07:57 UTC, achingbrain commented on package.json
> +    "reset": "aegir run clean && aegir clean **/node_modules **/package-lock.json",
It was good for it's time, but it's time has passed.

2023-02-03 07:59 UTC, achingbrain commented on package.json
> +    "aegir": "^38.1.0"
Yes, we want to allow patches and minors otherwise the maintenance overhead of keeping things up to date becomes overwhelming.

OTOH applications using libraries like this one should ship with lockfiles to prevent unexpected breakage from dependency churn.

2023-02-03 08:02 UTC, achingbrain commented on packages/helia/README.md
> +Loading this module through a script tag will make it's exports available as `Helia` in the global namespace.
It's the default name esbuild uses for the bundle output which it works out from the module name.

2023-02-03 08:04 UTC, achingbrain commented on packages/helia/README.md
> +- <https://ipfs.github.io/helia/modules/helia.html>
It's just how [remark](https://www.npmjs.com/package/remark) formats links.

See the [check-readme](https://github.com/ipfs/aegir/blob/master/src/check-project/check-readme.js) part of the aegir [check-project](https://github.com/ipfs/aegir/tree/master/src/check-project) command.

2023-02-03 08:06 UTC, achingbrain commented on packages/helia/package.json
> +    "npm": ">=7.0.0"
Fair, and also not strictly what we support, it should be LTS node.

Please PR [these lines](https://github.com/ipfs/aegir/blob/3e57c6a3cdd28a7e9bab2a1605831076481c1781/src/check-project/utils.js#L249-L252) to get it fixed rather than making changes here.

2023-02-03 08:15 UTC, achingbrain commented on packages/helia/package.json
> +  "types": "./dist/src/index.d.ts",
The default location for the index file is `src/index.ts` and the default location for it's types is `dist/src/index.d.ts` which is why this is here.

I think later versions of typescript will pull the types from the `"types"` key in the exports map but we've had problems with this in the past.

Please PR [this line](https://github.com/ipfs/aegir/blob/master/src/check-project/manifests/typescript.js#L22) to change this.

2023-02-03 08:19 UTC, achingbrain commented on packages/helia/package.json
> +    "@helia/interface": "~0.0.0",
* To allow consumption of the Helia API without depending on the Helia itself
* To allow alternative implementations of the Helia API - an RPC client, for example

2023-02-03 08:20 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +    const missingBlocks = filter(blocks, async ({ key }) => { return !(await this.has(key)) })
This should be enforced by a [linter](https://github.com/ipfs/eslint-config-ipfs)

2023-02-03 08:28 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +  private readonly child: Blockstore
I don't think so, no.  This is the blockstore that's passed to the `createHelia` factory function, which might be local [on-disk](https://github.com/ipfs/js-datastore-fs) storage, [level](https://github.com/ipfs/js-datastore-level), [s3](https://github.com/ipfs/js-datastore-s3) or something else.

2023-02-03 08:29 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +  }
Historically the performance of JS proxies has been awful.

2023-02-03 08:34 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +      return await this.bitswap.get(cid, options)
This is due to the [@typescript-eslint/return-await](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/return-await.md) linting rule and would need a PR to the [linting rules](https://github.com/ipfs/eslint-config-ipfs) to turn off.

2023-02-03 08:36 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +    )
See [yield-star-spacing](https://eslint.org/docs/latest/rules/yield-star-spacing)

2023-02-03 08:37 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +    void Promise.resolve().then(async () => {
If you `await` here it blocks the function.  The idea is to pull from bitswap and the wrapped blockstore in parallel.

2023-02-03 08:38 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +      }
Yes, the order matters here.

2023-02-03 08:38 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +  }
Historically the performance of JS proxies has been awful.

2023-02-03 08:40 UTC, achingbrain commented on packages/interop/test/fixtures/create-kubo.ts
> +  return controller
No good reason.

2023-02-04 15:52 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +      return await this.bitswap.get(cid, options)
See: https://github.com/ipfs/eslint-config-ipfs/issues/130

2023-02-06 13:18 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +    void Promise.resolve().then(async () => {
Not exactly - if you don't `await` an async function, and that function throws it will cause an unhanded promise rejection which can crash the process.  If you `.then` a resolved promise, and `.catch` the `.then` it will not.

2023-02-06 13:44 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +      }
It's not that straightforward - `getMany` takes a stream of CIDs and returns a stream of blocks - if you treat the input stream like an array, you'll end up waiting for the input stream to end before you emit any blocks which is likely to harm performance and not improve it.

Really you want the underlying blockstore to control the concurrency here - each blockstore implementation may have different performance constraints, so by calling it's `getMany` function and passing a stream in, that lets the blockstore control the parallelisation instead.

You can do things like map each input value to a function, then use [it-parallel](https://www.npmjs.com/package/it-parallel) with the `ordered` option to parallelise, but that essentially transforms one `getMany` into lots of `get`s which prevents the blockstore from operating in the way that is most efficient.

One thing to consider here is the link between input and output here is broken - we push data into the pushable as fast as possible, and the blockstore pulls from the pushable - if the blockstore is slow and the input stream is never-ending, eventually the process will fall over.

Anyway - this code is ported from js-ipfs, likely there are some performance improvements that can be made but I'd suggest not blocking this PR on that.

2023-02-06 13:51 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +  }
Can you point to some benchmarks please?

2023-02-06 21:06 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +    )
The default is defined by the linting rules which say [it can be either](https://github.com/standard/eslint-config-standard/blob/master/.eslintrc.json#L224) though I have to admit I struggle to see why one is better than the other.

2023-02-07 19:19 UTC, SgtPooki requested changes
Few requested changes regarding type consolidation and cleanup.. also for Helia, we should switch it to a class instead of an object literal.

2023-02-07 19:19 UTC, SgtPooki commented on packages/helia/src/utils/block-storage.ts
> +   * @param {AsyncIterable<CID> | Iterable<CID>} cids
We should really create a utility type for `AsyncIterable<T> | Iterable<T>`

2023-02-07 19:19 UTC, SgtPooki commented on packages/helia/src/utils/block-storage.ts
> +      }
Not blocking, but we should look into this at some point. While order may be important, we may be missing out on a significant performance gain by parallelizing these. Can we re-order them after parallelization? 

I imagine the performance gains here would be much more significant than for the 13 appIds I handled at https://github.com/ipfs-shipyard/ignite-metrics/blob/b8c041682ad6f399c91af36ff5a452cec07c88d6/reports/downloadDashboardData.ts#L39-L87

Regardless of blockstore implementation, we should increase our performance as much as possible. This would make a great case-study for some benchmarks in this repo. Slow blockstore.. fast blockstore, spotty blockstore..

2023-02-07 19:19 UTC, SgtPooki commented on packages/helia/test/index.spec.ts
> +  })
Is there a backlog task to track addressing this?

2023-02-07 19:19 UTC, SgtPooki commented on packages/interface/src/errors.ts
> +    super(message, 'NotAFileError', 'ERR_NOT_DIRECTORY')
```suggestion
    super(message, 'NotADirectoryError', 'ERR_NOT_DIRECTORY')
```

2023-02-07 19:19 UTC, SgtPooki commented on packages/interface/src/errors.ts
> +}
We should instantiate an Error instance that comes with a .trace either in this base, or the extended error types.

2023-02-07 19:19 UTC, SgtPooki commented on packages/interface/src/index.ts
> +  datastore: Datastore
```suggestion
export interface HeliaBase {
  /**
   * The underlying libp2p node
   */
  libp2p: Libp2p

  /**
   * Where the blocks are stored
   */
  blockstore: Blockstore

  /**
   * A key/value store
   */
  datastore: Datastore
}

export interface Helia extends HeliaBase {

```

2023-02-07 19:19 UTC, SgtPooki commented on packages/interop/test/fixtures/create-kubo.ts
> +    ipfsBin: isNode || isElectronMain ? goIpfs.path() : undefined,
TBH, i'm not a fan of these conditional args. There are so many variables, i'd rather configure the tests to create the kubo node with explicit configurations from the test itself. These conditional args were a large burden for gettig interface tests to pass when pulling kubo-rpc-client out of ipfs-http-client

2023-02-07 19:19 UTC, SgtPooki commented on packages/interop/test/fixtures/create-kubo.ts
> +            '/ip4/0.0.0.0/tcp/4002/ws'
should these ports be passed in or read from env var?

2023-02-07 19:22 UTC, SgtPooki commented on packages/helia/src/utils/block-storage.ts
> +    void Promise.resolve().then(async () => {
I don't think being consistent with async+await vs .then matters as much as doing the right thing for the code. Personally, I've fixed a few comments @whizzzkid has had regarding consistent async/await but sometimes a .then just feels correct. For syntactic sugar in most languages, it's often required to "reach into the guts" of that sugar to do something more technical. I think that should be okay for special circumstances.

However, when we do "reach into the guts" we should document why it's necessary. i.e. this convo should be documented into why we are doing this `Promise.resolve()... ` instead of simply awaiting things.

2023-02-07 19:23 UTC, SgtPooki commented on packages/helia/src/utils/block-storage.ts
> +    void Promise.resolve().then(async () => {
I do think pulling the anon function inside the `.then` here is a good call regardless of the .then/await decision.

2023-02-13 10:56 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +      }
> While order may be important, we may be missing out on a significant performance gain by parallelizing these. Can we re-order them after parallelization?

Yes, though again not without tradeoffs - see the paragraph about using it-parallel in my comment.

2023-02-13 11:47 UTC, achingbrain commented on packages/helia/src/index.ts
> +  })
It was TODO, needed to allow passing in a list of esoteric hashers so people can use more than just what's bundled with the multiformats module.

2023-02-13 11:57 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> + * datastore and may retrieve data from a remote Exchange.
I've updated the comment, hopefully it's clearer now.

2023-02-13 11:59 UTC, achingbrain commented on packages/interface/src/errors.ts
> +}
What's a `.trace`?

2023-02-13 12:03 UTC, achingbrain commented on packages/interop/test/fixtures/create-kubo.ts
> +            '/ip4/0.0.0.0/tcp/4002/ws'
They could be `0` tbh, we don't use them directly.

2023-02-13 12:07 UTC, achingbrain commented on packages/interop/test/fixtures/create-kubo.ts
> +    ipfsBin: isNode || isElectronMain ? goIpfs.path() : undefined,
All this is saying is invoke `goIpfs.path()` if the environment is node or the electron main process.

What is the burden this causes?

2023-02-13 12:16 UTC, achingbrain commented on packages/helia/src/utils/block-storage.ts
> +   * @param {AsyncIterable<CID> | Iterable<CID>} cids
It's called `AwaitIterable` in [interface-store](https://github.com/ipfs/js-ipfs-interfaces/blob/master/packages/interface-store/src/index.ts#L2), we can just use that one if it helps.

2023-02-13 14:34 UTC, achingbrain commented on packages/helia/src/index.ts
> +  }
The aim here is that there will never be any other methods added to the Helia type, all functionality will be built by modules that build on top of Helia so while I'm sympathetic to the maintenance argument, my hope is there won't be much maintenance necessary!

2023-02-13 14:34 UTC, achingbrain commented on packages/helia/test/index.spec.ts
> +  })
I've added tests

2023-02-13 14:35 UTC, achingbrain commented on packages/interface/src/index.ts
> +  datastore: Datastore
I don't follow the change here, why do we need both `Helia` and `HeliaBase` types?

2023-02-13 15:19 UTC, achingbrain commented on packages/helia/package.json
> +    "@helia/interface": "~0.0.0",
The Helia interface is very minimal and I don't see it changing much in the future, if at all.

It's not the same as `ipfs-core-api` so let's revisit this if it becomes a problem.

2023-02-13 15:48 UTC, achingbrain commented
Going to merge this to encourage some downstream experimentation - any subsequent internal refactors can be addressed separately.

2023-02-13 15:49 UTC, merged