docs: Update README.md
ipfs/helia pull request #34
Opened 2023-02-20 07:39 UTC by BigLep

Move the purpose/goals up top
Make clearer how to get involved
Use markdown TOC generator

2023-02-20 07:44 UTC, achingbrain requested changes

2023-02-20 07:44 UTC, achingbrain commented on README.md
> +<!-- TOC -->
The TOC is generated by [mdast-util-toc](http://npmjs.com/package/mdast-util-toc) as part of the [aegir check-project command](https://github.com/ipfs/aegir/blob/master/src/check-project/check-readme.js#L154-L156) and is consistent across all of our IPJS repos - any changes to the desired output format should be made in a PR to aegir that changes the config passed to `makeToc`, otherwise they will be overwritten next time that command is run.

2023-02-21 03:38 UTC, BigLep commented on README.md
> +<!-- TOC -->
ACK - thanks.  I have switched to use that.

2023-02-24 17:37 UTC, achingbrain commented on README.md
> +## Purpose and goals
```suggestion

## Purpose and goals
```

2023-02-24 17:39 UTC, achingbrain commented on README.md
> +Please find and comment on [the Roadmap here](https://github.com/ipfs/helia/issues/5).
```suggestion
## Roadmap

Please find and comment on [the Roadmap here](https://github.com/ipfs/helia/issues/5).
```

2023-02-24 17:39 UTC, achingbrain commented on README.md
> +* We are sharing about the progress at periodic [Helia Demos](https://lu.ma/helia).  This is a good place to find out the latest and learn of ways to get involved.  We'd love to see you there!
```suggestion
## Get involved

* We are sharing about the progress at periodic [Helia Demos](https://lu.ma/helia).  This is a good place to find out the latest and learn of ways to get involved.  We'd love to see you there!
```

2023-02-24 17:39 UTC, achingbrain commented on README.md
> +A lean, modular, and modern implementation of IPFS for the prolific JS and browser environments.
```suggestion
## Purpose and goals

A lean, modular, and modern implementation of IPFS for the prolific JS and browser environments.
```

2023-02-24 18:03 UTC, achingbrain approved these changes

2023-02-24 18:03 UTC, merged