Use path gateway in default gateways
ipfs/helia pull request #374
Opened 2024-01-10 12:20 UTC by 2color

fixes #347

2024-01-11 23:28 UTC, SgtPooki requested changes

2024-01-11 23:28 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/index.ts
> +  'https://ipfs.io',
We originally discussed not including `ipfs.io` in this list.

2024-01-11 23:28 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/index.ts
> +  'https://cloudflare-ipfs.com',
Why switch from cf-ipfs.com to cloudflare-ipfs.com?

2024-01-12 09:04 UTC, 2color commented on packages/block-brokers/src/trustless-gateway/index.ts
> +  'https://ipfs.io',
Why is that? Dweb.link and ipfs.io are backed by the same infra.

2024-01-15 17:40 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/index.ts
> +  'https://ipfs.io',
I believe the goal is to use ipfs.io gateway less. Plans were to use the new `someguy` / `rainbow` backed gateway.

2024-01-15 17:42 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/index.ts
> +  'https://cloudflare-ipfs.com',
Yeah, it makes sense now. Since cloudflare-ipfs.com doesn't support subdomains, it doesn't redirect the path routes to subdomains.

2024-01-16 10:53 UTC, 2color commented on packages/block-brokers/src/trustless-gateway/index.ts
> +  'https://ipfs.io',
As mentioned above, both ipfs.io and dweb.link are resolving to the same IP (209.94.90.1) and underlying infrastructure. Some of that infrastructure is already using rainbow. 

Are you suggesting that we don't include either one of `dweb.link` or `ipfs.io`?

2024-01-16 15:52 UTC, ns4plabs commented on packages/block-brokers/src/trustless-gateway/index.ts
> +  'https://ipfs.io',
We have a dedicated domain `trustless-gateway.link` for the trustless gateway which is backed by [rainbow](https://github.com/ipfs/rainbow)

2024-01-16 16:25 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/index.ts
> +  'https://ipfs.io',
trustless-gateway.link should prevent redirects as well:

```sh
curl -H "Accept: application/vnd.ipld.raw" "https://trustless-gateway.link/ipfs/QmTUAobz6YU1Ej5dTibodQPNtKk2TNnQek5TXHv13Dk2zq?format=raw" -vvv > QmTUAobz6YU1Ej5dTibodQPNtKk2TNnQek5TXHv13Dk2zq.json
```

2024-01-16 16:25 UTC, SgtPooki requested changes

2024-01-16 16:25 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/index.ts
> +  'https://ipfs.io',
```suggestion
  'https://trustless-gateway.link',
```

2024-01-16 16:49 UTC, 2color commented
Blocked until https://github.com/protocol/bifrost-community/issues/4 is resolved.

2024-01-30 23:46 UTC, SgtPooki commented
this should be ready to be merged now

2024-01-30 23:56 UTC, merged