feat: create @helia/verified-fetch
ipfs/helia pull request #392
Opened 2024-01-17 23:41 UTC by SgtPooki

Moving into Helia repo from https://github.com/ipfs/web3-fetch/pull/1

2024-01-17 23:45 UTC, SgtPooki commented on packages/verified-fetch/package.json
> +    "sinon-ts": "^2.0.0"
these need cleaned up, as much was copied over from @helia/utils

2024-01-17 23:45 UTC, SgtPooki commented on packages/verified-fetch/src/index.ts
> + * - IPNS URL
I think we should remove CID string and CID instance from possible resource arguments.

2024-01-17 23:45 UTC, SgtPooki commented on packages/verified-fetch/src/interface.ts
> + * Instead of passing a Helia instance, you can pass a list of gateways and routers, and a Helia instance will be created for you.
```suggestion
 * Instead of passing a Helia instance, you can pass a list of gateways and routers, and a HeliaHTTP instance will be created for you.
```

2024-01-17 23:45 UTC, SgtPooki commented on packages/verified-fetch/src/utils/get-content-type.ts
> +export const DEFAULT_MIME_TYPE = 'text/html'
we should decide on what mime-type makes sense if we cannot determine one.

2024-01-17 23:45 UTC, SgtPooki commented on packages/verified-fetch/src/verified-fetch.ts
> +  }
I don't believe we can use @helia/http for fetching this content the way @helia/block-brokers is currently set up. We will need to fetch from gateways directly for these without re-architecting @helia/http or block-brokers.

2024-01-17 23:45 UTC, SgtPooki commented on packages/verified-fetch/src/verified-fetch.ts
> +    response.headers.set('x-ipfs-protocol', 'ipfs')
headers set here so we can share them across methods. unique headers based on content-type should be set in appropriate methods

2024-01-18 13:58 UTC, 2color commented on packages/verified-fetch/README.md
> +`@helia/verified-fetch`` is a library that provides a fetch-like API for fetching content from IPFS. This library should act as a replacement for the `fetch()` API for fetching content from IPFS, and
```suggestion
`@helia/verified-fetch` is a library that provides a fetch-like API for fetching content from IPFS. This library should act as a replacement for the `fetch()` API for fetching content from IPFS, and will return a [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) object that can be used in a similar manner to the `fetch()` API. This means browser and HTTP caching inside browser main threads, web-workers, and service workers, as well as other features of the `fetch()` API should work in a way familiar to developers.
```

2024-01-18 14:05 UTC, lidel commented on packages/verified-fetch/src/utils/get-content-type.ts
> +export const DEFAULT_MIME_TYPE = 'text/html'
application/octet-stream

2024-01-18 14:20 UTC, achingbrain commented on packages/verified-fetch/README.md
> +  CreateHeliaHttpOnly({
```suggestion
import { createHelia as createHeliaHttpOnly } from '@helia/http'

const verifiedFetch = await createVerifiedFetch(
  createHeliaHttpOnly({
```

2024-01-18 14:35 UTC, lidel commented on packages/verified-fetch/src/index.ts
> + * - IPNS URL
Asking users who already have these to do extra work of prepending `ipfs://` feels like a papercut.
Is there harm in keeping them? Are we worried about typescript types breaking constantly?

2024-01-18 14:38 UTC, lidel commented on packages/verified-fetch/src/verified-fetch.ts
> +    response.headers.set('x-ipfs-protocol', 'ipfs')
Hm.. do we need to invent `x-ipfs-cid` and `x-ipfs-path`? 
[`X-Ipfs-Path`](https://specs.ipfs.tech/http-gateways/path-gateway/#x-ipfs-path-response-header) already includes protocol (ipfs or ipns), and if we want CIDs for sub-paths, there is [`X-Ipfs-Roots`](https://specs.ipfs.tech/http-gateways/path-gateway/#x-ipfs-roots-response-header)

2024-01-18 15:46 UTC, aschmahmann commented on packages/verified-fetch/src/verified-fetch.ts
> +  }
1. My suspicion is that we can do this can be done with helia/http by taking the blocks and assembling them into CARs and validating them
2. I don't suspect anyone will need support for this (at least in a browser environment) for quite a while. For now I'd just reject requests for `vnd.ipld.car` as unsupported

2024-01-18 16:35 UTC, 2color commented
As discussed, for a long (multiblock) UnixFS JSON, try https://cloudflare-ipfs.com/ipns/tokens.uniswap.org which resolves to `QmQJ8fxavY54CUsxMSx9aE9Rdcmvhx8awJK2jzJp4iAqCr`

2024-01-18 17:55 UTC, SgtPooki commented on packages/verified-fetch/README.md
> +const verifiedFetch = await createVerifiedFetch(
I've got that in my test but didn't update the readme yet. will do

2024-01-18 17:56 UTC, SgtPooki commented on packages/verified-fetch/src/index.ts
> + * - IPNS URL
The concern is the additional "path" argument that is required if a user provides a CID instance. We discussed during helia WG. I will remove `CID string` as an option and user who pass CID instances won't be able to provide a path

2024-01-18 20:40 UTC, SgtPooki commented
> As discussed, for a long (multiblock) UnixFS JSON, try [cloudflare-ipfs.com/ipns/tokens.uniswap.org](https://cloudflare-ipfs.com/ipns/tokens.uniswap.org) which resolves to QmQJ8fxavY54CUsxMSx9aE9Rdcmvhx8awJK2jzJp4iAqCr

@2color a test for this has been added and is working properly.

2024-01-18 20:50 UTC, SgtPooki commented on packages/verified-fetch/test/gateways.spec.ts
> +    // const encodedText = UnixFS.unmarshal(new Uint8Array(marshalledResponseData)).data
I'm doing this via https://github.com/ipfs/helia/pull/392/files#diff-12157866119b95f1b476d4e54ac9d3f22a24cc7e7af1a85f251c00c4dfbefcc6R135 now, but it's not sophisticated at all. I'm not sure when unixfs data for multipart content needs unmarshalled though.

2024-01-18 21:45 UTC, aschmahmann commented on packages/verified-fetch/src/verified-fetch.ts
> +    const asyncIter = this.unixfs.cat(cid, { path, signal: options?.signal })
Using `cat` here doesn't seem like  you want since you're returning the raw block. Instead you probably want:

https://github.com/ipfs/helia/blob/031519cea8e45a82272d3d56c7fd44f481184989/packages/unixfs/src/commands/utils/resolve.ts#L35

Followed by loading the block corresponding to the returned CID

2024-01-18 23:41 UTC, SgtPooki commented on packages/verified-fetch/src/verified-fetch.ts
> +    const asyncIter = this.unixfs.cat(cid, { path, signal: options?.signal })
that method isn't exported, so i've switched to `.stat` for now

2024-01-19 00:21 UTC, SgtPooki commented
FYI tests are failing when ran locally with `Failed to load resource: net::ERR_CONNECTION_REFUSED`. I need to find a better way to run a gateway that can serve this content, or a better way around writing tests to verify that we're getting the content we expect back.

2024-01-22 21:37 UTC, SgtPooki commented on packages/verified-fetch/src/verified-fetch.ts
> +    const asyncIter = this.unixfs.cat(cid, { path, signal: options?.signal })
opened https://github.com/ipfs/helia/issues/399 for exporting that method, since we would need that method (or similar) for `X-Ipfs-Roots`

2024-01-24 20:21 UTC, aschmahmann commented on packages/verified-fetch/src/verified-fetch.ts
> +        dnsOverHttps('https://dns.quad9.net/dns-query')
It doesn't look like https://dns.quad9.net supports cors 
![image](https://github.com/ipfs/helia/assets/2733228/03570a6a-1726-46af-9e14-d5dd84b46892)

2024-01-25 15:00 UTC, SgtPooki commented on packages/verified-fetch/README.md
> +    - `helia:verified-fetch:response:error` - An error occurred while building the response.
onProgress events should help answer the following questions:

* did I finish resolving IPNS name / peerId
* was I able to find the terminal element, if not, why not.
* were there any redirects?
* download progress for terminal elements (chunk counter?)
* did we find who has the data (providers)?

2024-01-25 15:19 UTC, SgtPooki commented on packages/verified-fetch/src/interface.ts
> +  // onProgress?: (progress: any) => void
see https://github.com/ipfs/helia/pull/392#discussion_r1466502990 for discussion around events to impl

2024-01-25 15:58 UTC, SgtPooki commented on packages/verified-fetch/README.md
> +    - `helia:verified-fetch:response:error` - An error occurred while building the response.
'if async custom work, should probably have async event':
custom onprogress:
* redirects?
* progress?

the rest should be piped up from other helia Modules used.

2024-01-25 16:12 UTC, SgtPooki commented on packages/verified-fetch/src/verified-fetch.ts
> +    const asyncIter = await this.unixfs.cat(cid, { path, signal: options?.signal })
This method is called/named incorrectly: ipldRaw doesn't mean unixfs

2024-01-25 18:57 UTC, SgtPooki commented on packages/verified-fetch/src/verified-fetch.ts
> +    this.helia = helia
we do, in src/index.ts. This class should not be consumed publicly

2024-01-25 21:39 UTC, SgtPooki commented
@lidel I did confirm that loading paths for HAMT-sharded directories does work with [helia-http-gateway using verified-fetch](https://github.com/ipfs/helia-http-gateway/pull/63)

<img width="1742" alt="image" src="https://github.com/ipfs/helia/assets/1173416/083c9487-9edc-4b15-bdf8-ad01ec60bfd8">

However, running a test locally against that hamt-sharded directory seem to take too long. it would be nice if we had a smaller car to use to verify for test environments. 

The local run of https://github.com/ipfs/helia/pull/403 also fails on my machine (it's a 64GB memory M1 Max)

2024-01-26 16:07 UTC, achingbrain commented on packages/interop/.aegir.js
> +async function createFixtureServer() {
Aegir does this for you - for an example see the use of [loadFixture](https://github.com/ipfs/js-ipfs/blob/bf1bc8b18d750d5591bdd575a6d0f4c067d61d0a/packages/interface-ipfs-core/src/utils/index.js#L3)

2024-01-26 16:14 UTC, achingbrain commented on packages/verified-fetch/README.md
> +`@helia/verified-fetch` is a library that provides a fetch-like API for fetching content from IPFS. This library should act as a replacement for the `fetch()` API for fetching content from IPFS, and
Everything from `# About` to the next L1 header (`# Install` here) needs to be in the `@packageDocumentation` block of `src/index.ts` as the contents of the readme will be overwritten by this documentation block when `npm run docs` is run.

2024-01-26 16:14 UTC, achingbrain commented on packages/verified-fetch/.aegir.js
> +export default {
This config file seem superfluous?

2024-01-26 16:16 UTC, achingbrain commented on packages/verified-fetch/README.md
> +### Configuration
All of this exposition needs to move into the `@packageDocumentation` block of `/src/index.ts`

2024-01-26 16:17 UTC, achingbrain commented on packages/verified-fetch/package.json
> +  "description": "A fetch-like API for IPFS content on the web.",
It'd probably be good to get the word "verified" or "trustless" in there?

2024-01-26 16:17 UTC, achingbrain commented on packages/verified-fetch/package.json
> +  "typesVersions": {
No need for `typesVersions` when there's only a single export.

2024-01-26 16:22 UTC, achingbrain commented on packages/verified-fetch/src/verified-fetch.ts
> +interface VerifiedFetchConstructorOptions {
For consistency, every other class in the monorepo has a split between components and init options in their constructor args.

If you like, components are things you use to get work done, init options are parameters that change how the work is done.

2024-01-26 16:25 UTC, achingbrain commented on packages/verified-fetch/src/interface.ts
> +import type { ResolveDnsLinkProgressEvents, ResolveProgressEvents } from '@helia/ipns'
I think most (all?) of these interfaces should be declared in the `index.ts` file.

As implemented they will not be exported from the module, so (for example) the exposed fetch factory function will accept an argument interface that cannot be referenced by consuming code.

This will work due to type overlap but it makes it harder to use and also means the types become undocumented in the generated API docs.

2024-01-26 16:26 UTC, achingbrain commented on packages/verified-fetch/src/interface.ts
> +export interface CidDetail {
CID is an acronym which we keep in capitals elsewhere:

```suggestion
export interface CIDDetail {
```

2024-01-26 16:26 UTC, achingbrain commented on packages/verified-fetch/src/interface.ts
> +export interface CidDetailError extends CidDetail {
CID is kept in capitals elsewhere:

```suggestion
export interface CIDDetailError extends CIDDetail {
```

2024-01-26 16:28 UTC, achingbrain commented on packages/verified-fetch/src/interface.ts
> +export interface VerifiedFetchOptions extends Omit<RequestInit, 'signal'>, AbortOptions, ProgressOptions<BubbledProgressEvents | VerifiedFetchProgressEvents> {
Any reason not to just take the `signal` option from `RequestInit` instead of `Omit`ing it, then adding it again with `AbortOptions`?

```suggestion
export interface VerifiedFetchOptions extends RequestInit, ProgressOptions<BubbledProgressEvents | VerifiedFetchProgressEvents> {
```

2024-01-26 16:32 UTC, achingbrain commented on packages/verified-fetch/src/utils/parse-url-string.ts
> +    if (cidOrPeerIdOrDnsLink.includes('.')) {
Usually we do this the other way round - try to resolve something as a domain last since it's the loosest format.

2024-01-26 16:37 UTC, achingbrain commented on packages/verified-fetch/src/verified-fetch.ts
> +        case 0x200:
Can you use the `code` property from the modules in question or some named constants?  We get these numbers wrong sometimes..

2024-01-26 16:41 UTC, achingbrain commented on packages/verified-fetch/src/index.ts
> +  if ((init as CreateVerifiedFetchWithOptions).gateways == null) {
You can disambiguate the `init` arg with something like:

```ts
function isHelia (obj?: any): obj is Helia {
  // test for the presence of known Helia properties
  return obj?.blockstore != null && obj?.datastore != null && ...
}
```

...then you can remove the casting.

2024-01-26 16:49 UTC, achingbrain commented on packages/verified-fetch/src/verified-fetch.ts
> +   * handle vnd.ipld.raw
`vnd.ipld.raw` is a block with opaque bytes, this method seems to treat the DAG as if it's something UnixFS-y?

2024-01-26 16:51 UTC, achingbrain commented on packages/verified-fetch/src/index.ts
> + * const json = await response.json()
Do you think we should call the variable in the example `fetch` to really hammer the point home about API familiarity?

```suggestion
 * const fetch = await createVerifiedFetch({
 *  gateways: ['http://mygateway.info', 'http://trustless-gateway.link']
 * })
 *
 * const cid = CID.parse('bafyFoo') // some image file
 * const response = await fetch(cid)
 * const json = await response.json()
```

2024-01-26 16:53 UTC, achingbrain requested changes
LGTM - there's bits of tidy up to be done internally but the API looks solid enough for an RC.

Comments are inline.

2024-01-26 17:49 UTC, SgtPooki commented on packages/verified-fetch/src/index.ts
> + * const json = await response.json()
I'm good with that, but we're shadowing the global fetch at this point which could cause confusion. Will wait for others' opinions before making this switch.

2024-01-26 17:50 UTC, SgtPooki commented on packages/verified-fetch/src/index.ts
> +  if ((init as CreateVerifiedFetchWithOptions).gateways == null) {
typeguard ftw

2024-01-26 17:50 UTC, SgtPooki commented on packages/verified-fetch/src/verified-fetch.ts
> +        case 0x200:
100% good call

2024-01-26 17:51 UTC, SgtPooki commented on packages/verified-fetch/src/utils/parse-url-string.ts
> +    if (cidOrPeerIdOrDnsLink.includes('.')) {
can do

2024-01-26 17:52 UTC, SgtPooki commented on packages/verified-fetch/src/interface.ts
> +export interface VerifiedFetchOptions extends Omit<RequestInit, 'signal'>, AbortOptions, ProgressOptions<BubbledProgressEvents | VerifiedFetchProgressEvents> {
I wanted to support future cases where AbortOptions changes, since most Helia methods, and Helia module's methods, take an object with an interface extending AbortOptions. With that said, this module is a little bit different than others, so I think it would be fine if we left with RequestInit

2024-01-26 17:54 UTC, SgtPooki commented on packages/verified-fetch/package.json
> +  }
no, this is left-over from when I was trying to use `file-type` for mime-types. will remove

2024-01-26 17:55 UTC, SgtPooki commented on packages/verified-fetch/.aegir.js
> +export default {
will remove. this was still left from before I moved tests to `interop`

2024-01-26 17:56 UTC, SgtPooki commented on packages/verified-fetch/README.md
> +`@helia/verified-fetch` is a library that provides a fetch-like API for fetching content from IPFS. This library should act as a replacement for the `fetch()` API for fetching content from IPFS, and
I wasn't sure exactly how that would work. Thanks, will update.

2024-01-26 19:08 UTC, SgtPooki commented on packages/interop/.aegir.js
> +async function createFixtureServer() {
it would be nice if aegir provided a stream so it wasn't sync. Since for this use-case, in the browser it needs to be fetched from the browser, loaded into kubo-rpc-client, then passed back to kubo node. Would be great if it was streamed all the way through.

2024-01-26 21:21 UTC, SgtPooki commented on packages/verified-fetch/src/utils/parse-url-string.ts
> +    if (cidOrPeerIdOrDnsLink.includes('.')) {
[`a34119b` (#392)](https://github.com/ipfs/helia/pull/392/commits/a34119b5066f66d18597bed3dd98f8e8d36e3f06)

2024-01-30 01:06 UTC, SgtPooki commented on packages/verified-fetch/src/verified-fetch.ts
> +      for (const rootFilePath of ['index.html', 'index.htm', 'index.shtml']) {
I don't think we're providing any SSI from gateways, so it would be up to a specific service to implement those, but it's worth thinking about what we want to consider root files.

I think the root list should be specified in specs.ipfs.tech if different from typical website loading, and not configurable.

2024-01-30 16:32 UTC, lidel commented on packages/verified-fetch/src/verified-fetch.ts
> +        dnsJsonOverHttps('https://dns.google/resolve')
Sgtm, since we only talk to Cloudflare and Google anyway, we can talk JSON with them. If someone needs binary DNS, or ENS, they can pass custom resolver they trust (for ENS DoH at https://resolver.cloudflare-eth.com/dns-query or implement something with https://github.com/a16z/helios)

2024-01-30 16:35 UTC, lidel commented on packages/verified-fetch/src/verified-fetch.ts
> +      for (const rootFilePath of ['index.html', 'index.htm', 'index.shtml']) {
Since https://specs.ipfs.tech/http-gateways/path-gateway/#response-payload only looks for `index.html`, and it been this way for newarly a decade, no need to check for anything else.

2024-01-30 16:40 UTC, lidel commented on packages/interop/src/verified-fetch-json.spec.ts
> +    it('handles uniswap tokens list json', async () => {
```suggestion
    it('.json() supports UnixFS-chunked JSON file', async () => {
```

2024-01-30 16:47 UTC, SgtPooki commented
latest helia/verified-fetch is not resolving some of the dApps Ed provided in the dApps working group (https://hackmd.io/LS4eUSZXTriQ0j8UIjDl4A?view#Agenda)

❌ `/ipns/app.aave.com` is failing ipns resolution even though we are getting an answer back:

<img width="1973" alt="image" src="https://github.com/ipfs/helia/assets/1173416/a3a73d0e-1416-413a-ad2b-672bb267ab34">

✅ /ipns/app.spark.fi
❌ /ipns/app.olympusdao.finance

2024-01-30 16:47 UTC, lidel commented on packages/verified-fetch/test/verified-fetch.spec.ts
> +    it('should return dag-json encoded CID', async () => {
nit: while we at it, can we add the same `.json()` read test for `dag-cbor` too? CID can be produced by bellow command

```console
$ echo -n '{"hello":"world"}' | ipfs dag put --store-codec dag-cbor
bafyreidykglsfhoixmivffc5uwhcgshx4j465xwqntbmu43nb2dzqwfvae
```

2024-01-30 17:00 UTC, lidel commented on packages/verified-fetch/README.md
For the initial release, it would be useful to demonstrate value added by the library by having examples similar to https://github.com/ipfs/helia/tree/main/packages/ipns#example---getting-started right in the README.

We already have tests for these, just need to add HTML+JS snippets to README:


- `dag-cbor` read via `.json()`
- UnixFS JSON read via `.json()`
- plain text file in UnixFS HAMT read via `.text()`
- `<img>` having `src` set to `data:image/jpg;base64,[...]` with payload read via `.arrayBuffer()`

2024-01-30 17:30 UTC, SgtPooki commented on packages/verified-fetch/test/verified-fetch.spec.ts
> +    it('should return dag-json encoded CID', async () => {
added: [`0e0c287` (#392)](https://github.com/ipfs/helia/pull/392/commits/0e0c2870b54cb0fe41e19738abf5e30fc50987e1)

2024-01-30 17:32 UTC, SgtPooki commented on packages/verified-fetch/README.md
the examples are in @packageDocumentation of src/index.ts now and will be copied over to README when merged

2024-01-30 19:20 UTC, SgtPooki commented
> /ipns/app.aave.com is failing ipns resolution even though we are getting an answer back:

I created a demo for testing IPNS resolution at https://codepen.io/SgtPooki/pen/ZEPrJYp?editors=1011

```
Log:
dnslink:query: "app.aave.com"
dnslink:query: "app.aave.com"
dnslink:answer: {"Status":0,"TC":false,"RD":true,"RA":true,"AD":true,"CD":false,"Question":[{"name":"app.aave.com.","type":16}],"Authority":[{"name":"aave.com.","type":6,"TTL":1800,"data":"art.ns.cloudflare.com. dns.cloudflare.com. 2332124099 10000 2400 604800 1800"}],"Comment":"Response from 173.245.59.102."}
dnslink:query: "_dnslink.app.aave.com"
dnslink:answer: {"Status":0,"TC":false,"RD":true,"RA":true,"AD":true,"CD":false,"Question":[{"name":"_dnslink.app.aave.com.","type":16}],"Answer":[{"name":"_dnslink.app.aave.com.","type":16,"TTL":300,"data":"dnslink=/ipfs/bafybeifcaqowoyito3qvsmbwbiugsu4umlxn4ehu223hvtubbfvwyuxjoe/"}],"Comment":"Response from 172.64.32.152."}
dnslink:answer: {"Status":0,"TC":false,"RD":true,"RA":true,"AD":true,"CD":false,"Question":[{"name":"app.aave.com","type":16}],"Authority":[{"name":"aave.com","type":6,"TTL":1800,"data":"art.ns.cloudflare.com. dns.cloudflare.com. 2332124099 10000 2400 604800 1800"}]}
dnslink:cache: "/ipfs/bafybeifcaqowoyito3qvsmbwbiugsu4umlxn4ehu223hvtubbfvwyuxjoe/"

Result: Invalid value
```

2024-01-31 19:19 UTC, SgtPooki commented on packages/verified-fetch/src/verified-fetch.ts
> +        dnsJsonOverHttps('https://dns.google/resolve')
With the current structure of the code, they cannot override DNS/ENS resolution, as the class `VerifiedFetch` is not publicly consumable, and the `createVerifiedFetch` function only supports gateways/routers parameters. We could add later if someone desires, but for now they would need to resolve the CIDs outside of this method, and then query IPFS/IPNS using this library

2024-02-01 14:24 UTC, lidel commented on packages/verified-fetch/src/index.ts
> + * const blob = await response.blob()
Maybe go extra step?
```suggestion
 * const blob = await response.blob()
 * const img = document.createElement('img')
 * img.src = URL.createObjectURL(blob)
 * document.body.appendChild(img)
```

2024-02-01 14:24 UTC, lidel commented on packages/verified-fetch/src/index.ts
> + * const response = await fetch('ipns://mydomain.com/path/to/video.mp4')
I think we should avoid video here, because videos require efficient seeking, and that can be done with range requests, which we don't have yet.

Let's make this about streaming generic "big file" instead:

```suggestion
 * @example Using ipns protocol to stream a big file
 *
 * ```typescript
 * import { createVerifiedFetch } from '@helia/verified-fetch'
 *
 * const fetch = await createVerifiedFetch({
 *  gateways: ['http://mygateway.info', 'http://trustless-gateway.link']
 * })
 * const response = await fetch('ipns://mydomain.com/path/to/very-long-file.log')
```

2024-02-01 14:24 UTC, lidel commented on packages/verified-fetch/src/index.ts
> + * const videoStreamReader = await response.body.getReader()
nit: I think we forgot to close this code block?
````suggestion
 * const bigFileStreamReader = await response.body.getReader()
``` 
````

2024-02-01 14:24 UTC, lidel commented on packages/verified-fetch/src/index.ts
> + *  gateways: ['http://mygateway.info', 'http://trustless-gateway.link']
nit: some examples use `http://`, some use domain alone. I think we should switch everything to `https://` for consistency and to avoid mixed-content warnings.

2024-02-01 14:24 UTC, lidel commented on packages/verified-fetch/src/index.ts
> + *  gateways: ['mygateway.info', 'trustless-gateway.link']
nit: change to `mygateway.example.net` (https://en.wikipedia.org/wiki/Example.com)

2024-02-01 17:58 UTC, SgtPooki commented on packages/verified-fetch/src/verified-fetch.ts
> +      const codecHandler = this.codecHandlers[cid.code]
Before we call formatHandler or codecHandler, if there is a path, we should be letting `ipfs-unixfs-exporter` handle the walk to the terminal element, and potentially parsing of the terminal element if not handled by `ipfs-unixfs-exporter`

2024-02-01 18:04 UTC, SgtPooki commented on packages/verified-fetch/src/index.ts
> + * const blob = await response.blob()
I thought about adding that but ended up getting distracted I guess, good call :)

2024-02-01 21:18 UTC, SgtPooki commented
FYI @achingbrain @lidel @aschmahmann that ipfs-unixfs-exporter is now being used for walking paths

2024-02-02 11:01 UTC, achingbrain approved these changes

2024-02-02 11:46 UTC, merged