fix!: replace dag walkers with generic CID extraction from blocks
ipfs/helia pull request #447
Opened 2024-02-22 18:21 UTC by achingbrain

Replace the codec-specific `.dagWalkers` property with a generic dag walker internally that uses the `Block` interface from the `multicodecs` module.

- Removes the `.dagWalkers` property from the Helia interface
- Adds `getCodec` and `getHasher` to retrieve codecs and hashers by code
- Adds `loadCodec` and `loadHasher` options to allow sync or async loading of extra codecs/hashes in addition to staticlly configured ones in the `codecs`/`hashers` keys

BREAKING CHANGE: the `.dagWalkers` property has been removed

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

2024-04-03 00:06 UTC, SgtPooki requested changes
a few things that could be changed, not sure if the networked-storage accepting an additional arg was done explicitly for some reason though

2024-04-03 00:06 UTC, SgtPooki commented on packages/utils/test/fixtures/create-dag.ts
> +        await createAndPutBlock(dagCbor.code, dagCbor.encode(child), blocks)
I know this is just a test fixture, but do we want to remove the ability to use any codec?

2024-04-03 00:06 UTC, SgtPooki commented on packages/utils/test/utils/networked-storage.spec.ts
> +    }, getHasher())
```suggestion
      ],
      getHasher
    })
```

2024-04-03 10:52 UTC, achingbrain commented on packages/car/src/index.ts
> +    const block = createUnsafe({ bytes, cid, codec })
We need a `Block` instance to call `.links()` on it.

`createUnsafe` doesn't verify that the block hash matches the block data, which is a (potentially) expensive operation, it just creates the block.

2024-04-03 11:05 UTC, achingbrain commented on packages/utils/test/fixtures/create-dag.ts
> +        await createAndPutBlock(dagCbor.code, dagCbor.encode(child), blocks)
The problem is creating a layered DAG depends on the codec - different codecs will implement this in different ways.

Previously we were only ever using one codec so it was a bit misleading.

2024-04-11 10:30 UTC, SgtPooki commented on packages/car/src/index.ts
> +    const block = createUnsafe({ bytes, cid, codec })
For the sake of verified-fetch, where do we verify the block hash matches the data after the changes in this PR?

2024-08-01 15:23 UTC, SgtPooki commented
we need to run benchmarks to ensure no perf regression

2024-09-13 17:02 UTC, achingbrain commented on packages/car/src/index.ts
> +    const block = createUnsafe({ bytes, cid, codec })
The blockstore should only give us the bytes that match the hash so there's no change necessary there.

2024-09-16 07:54 UTC, achingbrain commented
Perf seems fine - the benchmark added by https://github.com/ipfs/helia/pull/633 shows comparable performance between this branch and main.

2024-09-16 08:45 UTC, merged