chore: order of releases in changelog
ipfs/helia pull request #492
Opened 2024-04-09 13:58 UTC by 2color

## Title

2024-04-09 19:02 UTC, achingbrain commented
We've been through a couple of different release tools which format things differently, and code has been moved around without trimming the release logs, it's a bit of a mess.

2024-04-09 19:06 UTC, SgtPooki requested changes
we should probably try to re-generate the changelog completely using semantic-release.

2024-04-09 19:06 UTC, SgtPooki commented on packages/helia/CHANGELOG.md
> +    * @helia/block-brokers bumped from ^2.0.0 to ^2.0.1
it looks like there's a trailing `dependencies` below this that's actually a part of `### [2.0.1](https://www.github.com/ipfs/helia/compare/helia-v2.0.0...helia-v2.0.1) (2023-08-16)`

2024-04-09 20:21 UTC, SgtPooki commented
@achingbrain if we remove the changelogs in https://github.com/ipfs/helia/pull/483 can we get release-please to regenerate the full changelog?

2024-04-10 12:40 UTC, achingbrain commented
I don't know tbh, but my guess would be no.  I think it only considers changes since the last release tag, otherwise we'd see CI releases failing all over the place due to GitHub applying rate limiting (this happens when you stuff up the release-please config, for example).

2024-04-15 12:08 UTC, achingbrain commented
Ok, I've updated the formatting of all changelogs to be consistent with the latest release tool.

I've also re-tagged all the old releases from the `@helia/foo-vNNN` format to `foo-vNNN` and removed the old tags so everything's consistent.

Please delete your local tags in any cloned copy of helia you have and fetch the updated list (this will prevent you re-creating the old tag formats if you accidentally run `git push --tags`, for example):

```console
$ git tag -l | xargs git tag -d
$ git fetch
```

Hopefully going forwards everything autogenerated will be done just so.

2024-04-15 12:09 UTC, achingbrain approved these changes

2024-04-15 12:09 UTC, merged