fix: prevent duplicate trustless-gateway reqs
ipfs/helia pull request #503
Opened 2024-04-18 23:14 UTC by SgtPooki

- chore: add @types/polka
- feat: getStats() returns trustless gateway stats

## Title

fix: prevent duplicate trustless-gateway reqs

## Description

Fixes https://github.com/ipfs-shipyard/service-worker-gateway/issues/104

This PR fixes issues brought up in service-worker-gateway where sub-resources end up causing multiple requests to a trustless gateway for the root CID.

## Notes & open questions

I feel like the blockstore should handle this and ensure requests that depend on a root CID are deduped, but since trustless-gateways may be used outside of the context of blockstores, I believe we still need this improvement.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-04-18 23:15 UTC, SgtPooki reviewed
self review of the code so far that should fail CI test because fix isn't pushed yet.

2024-04-18 23:20 UTC, SgtPooki commented
note the failure which https://github.com/ipfs/helia/actions/runs/8745897909/job/24001821684?pr=503#step:5:793 [`97a05e4` (#503)](https://github.com/ipfs/helia/pull/503/commits/97a05e468f5dfbe642cecc6fa17fb370574c6be5) should fix

2024-04-18 23:49 UTC, SgtPooki reviewed
self review of code entirety

2024-04-18 23:49 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +      this.log.error('failed to get block for %c from %s', cid, gwUrl, cause)
idk if we didn't log errors here for a specific reason, but it feels like we should be logging the `cause` error so we can get details if needed.

2024-04-18 23:49 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +          return new Uint8Array(await res.arrayBuffer())
we need to fully encapsulate the request and response processing to ensure we're not attempting to consume the body twice. open to ideas of better methods.

2024-04-19 10:50 UTC, 2color commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +          return new Uint8Array(await res.arrayBuffer())
Since you immediately handle the promise and don't expose `Response` object, where's the risk of the body getting consumed twice?

2024-04-19 11:29 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +          return new Uint8Array(await res.arrayBuffer())
There isnt anymore. In my first iteration i was only saving resp promise (without arrayBuffer handling) to the map.

This was more of a note about why we're doing promise.then without any awaits here

2024-04-19 11:31 UTC, SgtPooki commented
One thing I thought of after stepping away last night: we should probably use finally to remove entry from map

2024-04-19 14:18 UTC, achingbrain commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +      let pendingResponse: Promise<Uint8Array> | undefined = this.#pendingResponses.get(gwUrl.toString())
We should dedupe responses based on a canonical stringification of the multihash of the CID (base64 or something) rather than then requested URL, because you can request two CIDs with different versions/codecs but they'd resolve to the same block.

2024-04-19 14:27 UTC, achingbrain commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +      this.log.error('failed to get block for %c from %s', cid, gwUrl, cause)
It doesn't hurt, but in the places this method is invoked from the caller will also log the error so you can end up with duplicated stacks in the logs which can be very noisy.

2024-04-19 14:28 UTC, achingbrain commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +  #pendingResponses = new Map<string, Promise<Uint8Array>>()
I'm not sure anything is ever being removed from this map - there doesn't appear to be a `this.#pendingResponses.delete` anywhere in this PR so it will grow until the process falls over.

2024-04-19 14:29 UTC, achingbrain requested changes
Seems reasonable, comments inline but please ensure things are removed from the pending responses map as it'll cause a memory leak as implemented.

2024-04-19 20:57 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +  #pendingResponses = new Map<string, Promise<Uint8Array>>()
Good eye. I had it in there and didnt realize i lost it when refactoring to fix dupe body reads

2024-04-20 00:04 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +      let pendingResponse: Promise<Uint8Array> | undefined = this.#pendingResponses.get(gwUrl.toString())
I put a codepen together to try and play with how this is done, and had some helpful tips from Adin to get me going

https://codepen.io/SgtPooki/pen/XWQygKB?editors=1111

it would be interesting to see where this falls down.

Also, is it just me that thinks it would be useful to export a blessed "are these CIDs referencing the same bytes" toString() function from multiformats?

2024-04-20 00:06 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +      this.log.error('failed to get block for %c from %s', cid, gwUrl, cause)
will remove

2024-04-20 00:12 UTC, SgtPooki reviewed
self review after addressing all comments

2024-04-20 00:12 UTC, SgtPooki commented on packages/block-brokers/test/trustless-gateway.spec.ts
> +  it('does not trigger new network requests if the same cid request is in-flight', async function () {
this test was renamed in the last iteration from "[...] same block [...]" to "[...] same cid [...]" because we're not actually testing the uniqueBlock functionality here where we would prevent requests given separate CIDs if they're referencing the same bytes.

2024-04-20 00:17 UTC, SgtPooki commented on packages/block-brokers/src/trustless-gateway/trustless-gateway.ts
> +      let pendingResponse: Promise<Uint8Array> | undefined = this.#pendingResponses.get(gwUrl.toString())
Leaving this PR open to make sure you take a peek at this before I merge

2024-04-20 16:07 UTC, achingbrain approved these changes

2024-04-20 16:07 UTC, merged