Skips exporting duplicate blocks as they are encountered
ipfs/helia pull request #557
Opened 2024-06-12 17:38 UTC by jtsmedley

## Title
Skip exporting duplicate blocks in @helia/car

## Description
When calling export on an @helia/car instance the yielded export contains duplicate blocks.  This PR skips yielding duplicate blocks resulting in compact CAR files.

## Notes & open questions

Added a SET to track which CID(s) have already been written to the stream.  Might need to add an option to toggle behavior if any users are relying on duplicate blocks in the output of CAR exports.

## Change checklist

- [Y] I have performed a self-review of my own code
- [Y] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [N] I have added tests that prove my fix is effective or that my feature works

2024-06-12 18:21 UTC, jtsmedley commented
Fixes #556

2024-06-12 18:27 UTC, SgtPooki requested changes
Thanks so much for submitting this. The code changes look fine to me, but CI ~~is~~ was failing. I would love to get thoughts from @lidel and @achingbrain on this one before proceeding. Additional thoughts below:

### Some car specifications

*carv1* - https://ipld.io/specs/transport/car/carv1/#duplicate-blocks
*carv2* - https://ipld.io/specs/transport/car/carv2/

It doesn't seem specified that duplicate blocks should or should not be included, but the only reason I can think to include them would be issues around https://ipld.io/specs/transport/car/carv1/#determinism. 

--- 

Maybe carv1 would require duplicate blocks for the final car to be the same as ones folks expect (and to rebuild dags that a CAR may represent), but with v2, it should be okay to remove them? 

I'm not sure that we're clear which spec we're attempting to adhere to with `@helia/car`.

2024-06-12 19:24 UTC, jtsmedley commented
For the sake of consistency Kubo does not export duplicate blocks.  At least from my limited testing.

2024-06-12 20:36 UTC, lidel commented
## What specs say?

Last time we looked into this the default behavior is left unspecified, and trustless gateway responses have explicit note about this:

- https://specs.ipfs.tech/http-gateways/trustless-gateway/#car-format-parameters-and-determinism

Gateway's CAR responses in [Kubo](https://github.com/ipfs/kubo) and [Rainbow](https://github.com/ipfs/rainbow/) (both backed by `boxo/gateway`) do not include duplicates by default.

There is `dups` parameter that can be used for making this explicit, allowing for signaling duplicate presence in response via `Content-Type` header params:
- https://specs.ipfs.tech/http-gateways/trustless-gateway/#car-dups-content-type-parameter
- https://specs.ipfs.tech/http-gateways/trustless-gateway/#car-format-signaling-in-request

Kubo/Rainbow use it to signal the response does NOT have duplicates.

## Sidenote: When are duplicates useful?

Duplicates have niche utility when you have a light client that has limited memory, so it can't cache blocks for later user, and has to “consume” blocks by unpacking data on the fly, and then discarding them (no blockstore, no cache, even in-memory). 

Such client would explicitly opt-in for receiving duplicates via `dups=t`. 
FWIW as of today, I am not aware of any clients that require this behavior, every client is usually smart enough to spawn follow-up `application/vnd.ipld.raw` request for any missing blocks, as this works with every gateway.

## On this PR

I think the only concern here is that `writtenBlocks` could grow in size and become DoS / OOM vector if the user tricks the system into exporting a big DAG with many duplicated CIDs.

Having the ability to control this at the library level (and disable deduplication, and the memory cost that comes with it) would be nice, but can be added once this becomes an actual and not theoretical problem.

2024-06-13 14:32 UTC, achingbrain commented
> I think the only concern here is that writtenBlocks could grow in size and become DoS / OOM vector if the user tricks the system into exporting a big DAG with many duplicated CIDs.

This can be mitigated by using a filter instead of a set, that way we don't need to store every CID encountered.

See [createScalableCuckooFilter](https://libp2p.github.io/js-libp2p/functions/_libp2p_utils.filters.createScalableCuckooFilter.html) in `@libp2p/utils`

```ts
import { createScalableCuckooFilter } from '@libp2p/utils/filters'

const filter = createScaleableCuckooFilter(maxItems, errorRate)

filter.has(bytes) // returns boolean
filter.add(bytes) // `.has` will probably now return `true`
```

The only thing to consider is the reliability of the filter.  False positives are possible but false negatives are not.  That is, if `.has` returns `false` the item is definitely not present.  If it returns `true` then the probability of the item being present is a factor of the `errorRate`.

The implementation should be structured so that there may be the (very) occasional duplicate block but there should never be a missed block.

2024-06-13 16:17 UTC, achingbrain commented
Good to know about the Kubo behaviour too, we should align with that though an `allowDuplicateBlocks: boolean` option would be good to have.

2024-06-13 16:24 UTC, jtsmedley commented
I need the `allowDuplicateBlocks: boolean` option anyways so I will go ahead and add that into this PR to round it out.

2024-06-17 12:18 UTC, jtsmedley commented
In this PR I am sticking as a set as I need no duplicates in the resulting CAR files and I need that to be consistent always.

2024-06-18 11:16 UTC, achingbrain requested changes
This needs to use a filter instead of a set as the set will cause the process to OOM for very large or streaming CAR files.

If making the filter reliable enough for the use case is a concern you may wish to expose a way to configure it or otherwise pass a preconfigured one in, since the size of it will largely be dictated by the size of the DAGs in the CAR being exported.

Can you please also add some tests that ensure there are no regressions around the `allowDuplicateBlocks` option.

2024-06-19 19:27 UTC, jtsmedley commented
Switched to passing in an external filter to allow the consumer to choose how blocks are filtered without a specific purpose.

`blocksFilter: Filter(@libp2p/utils/filters)`

2024-06-26 19:11 UTC, jtsmedley commented
Are any other changes needed?

2024-07-19 15:36 UTC, achingbrain commented
Apologies for the radio silence, this fell by the wayside while prepping for [IPFS Camp](https://2024.ipfs.camp/).  Normal service will resume on Monday!

2024-07-19 17:09 UTC, SgtPooki commented
seems like just a merge from main will fix CI here thanks to https://github.com/ipfs/helia/pull/572

2024-07-19 17:24 UTC, SgtPooki reviewed
this code seems much safer than previous.. two small suggestions.

2024-07-19 17:24 UTC, SgtPooki commented on packages/car/src/index.ts
> +            if (options?.blockFilter.has(cid.toString())) {
nit: typically we would use `options?.blockFilter != null`

2024-07-19 17:24 UTC, SgtPooki commented on packages/car/src/index.ts
> +            options?.blockFilter.add(cid.toString())
`options.blockFilter` is guaranteed to be type `Filter` in this branch

```suggestion
            options.blockFilter.add(cid.toString())
```

2024-07-19 17:24 UTC, SgtPooki commented on packages/car/test/index.spec.ts
> +  it('exports a car file with duplicates', async () => {
@achingbrain should we merge these two tests and export one with filter and one without?

2024-07-25 18:51 UTC, SgtPooki commented
i think the error at https://github.com/ipfs/helia/actions/runs/10043251811/job/27755609508?pr=557#step:4:183 is caused by https://github.com/multiformats/js-multiformats/issues/300

2024-07-26 15:06 UTC, SgtPooki approved these changes

2024-07-26 17:10 UTC, achingbrain requested changes
This is great, thanks for opening this.

Just a few stylistic nits but LGTM.

2024-07-26 18:07 UTC, jtsmedley commented on packages/car/src/index.ts
> +          }
I actually found I had issues passing in filters with bytes and that it seemed to be doing an object reference comparison on the bytes versus comparing the contents.

2024-07-26 18:30 UTC, achingbrain commented on packages/car/src/index.ts
> +          }
You can see the conversion from `string` to `Uint8Array` here: https://github.com/libp2p/js-libp2p/blob/main/packages/utils/src/filters/cuckoo-filter.ts#L112

It hashes the incoming item [here](https://github.com/libp2p/js-libp2p/blob/main/packages/utils/src/filters/cuckoo-filter.ts#L116C15-L116C25) and uses the hash to find the bucket that contains the fingerprint - no object reference comparison involved.

If you store a string the conversion will be slightly different as the string will be a base32 or base58btc encoded string that gets turned into a `Uint8Array`, which means you won't dedupe two CIDs with different codecs/versions have the same multihash.

Could you go into a bit more detail of the issue you encountered?

2024-07-26 19:13 UTC, jtsmedley commented on packages/car/src/index.ts
> +          }
I feel like I may have been doing something wrong in the process of development.  Give me till Monday and I will perform a full test again using the bytes of the multihash as I may have been using the bytes of the CID instead which obviously would result in a failed has check.

2024-07-29 23:13 UTC, jtsmedley commented
Confirmed no errors on my side using the bytes of the multihash once I switched from using a built in Set to using the ScalableCuckooFilter.  Built in SET performs comparisons on bytes by reference versus looking at each pointer.

No blocker from me anymore

2024-07-31 13:41 UTC, merged