chore: update benchmarks
ipfs/helia pull request #590
Opened 2024-09-06 12:10 UTC by achingbrain

The bugs stopping WebRTC and WebTransport from being testable in browsers have been fixed and shipped so they can be added to the suite.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-09-06 15:04 UTC, SgtPooki requested changes

2024-09-06 15:04 UTC, SgtPooki commented on benchmarks/transports/src/tests.ts
> +      }
this block will ensure we're only testing an implementation against itself. Is this supposed to be `===`?

2024-09-07 11:06 UTC, achingbrain commented on benchmarks/transports/src/tests.ts
> +      }
Ah, no - left that in by accident

2024-09-11 07:06 UTC, achingbrain commented on benchmarks/transports/src/tests.ts
> +
```suggestion
```

2024-09-11 07:07 UTC, achingbrain commented on benchmarks/transports/src/runner/helia/recipient.ts
> +  console.error(err)
```suggestion
} catch {
```

2024-09-13 16:13 UTC, merged